#!/usr/bin/env bash

# Generated by Grimoire V2
# Profile: gibeytech

sudo pacman -S git openssh hyprpicker wl-clipboard grim slurp kitty fish neovim obsidian ghostty python nodejs npm git lazygit docker docker-compose virt-manager qemu-full libvirt dnsmasq bridge-utils
yay -S brave-bin visual-studio-code-bin
