#!/usr/bin/env bash

# Generated by Grimoire V2
# Profile: advanced

sudo pacman -S ghostty fish neovim python nodejs npm git lazygit docker docker-compose virt-manager qemu-full libvirt dnsmasq bridge-utils
yay -S brave-bin
