background {
    color = rgba(22, 1a, 1a, 1.0)
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(f8, f8, f2, 1.0)

    font_size = 80

    position = 0, 90
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] echo "$(date +'%A %d %B %Y')"
    color = rgba(f8, f8, f2, 0.7)

    font_size = 22

    position = 0, 25
    halign = center
    valign = center
}

input-field {
    size = 250, 50

    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgba(e0, 78, 9a, 1.0)
    inner_color = rgba(2d, 20, 20, 1.0)
    font_color = rgba(f8, f8, f2, 1.0)

    position = 0, -80
    halign = center
    valign = center
}

label {
    text = Grimoire V2
    color = rgba(e0, 78, 9a, 1.0)

    font_size = 18

    position = 0, -145
    halign = center
    valign = center
}
