local Execute = {}

local Packaging = require("packaging")
local Validate = require("installer.validate")

local function assert_valid(config)
    local result = Validate.check(config)

    if result.valid then
        return true
    end

    error(
        "Invalid installation config:\n- "
            .. table.concat(result.errors, "\n- ")
    )
end

function Execute.dry_run(config)
    assert_valid(config)

    local lines = {}

    table.insert(lines, "=================================")
    table.insert(lines, "      Grimoire V2 Dry Run")
    table.insert(lines, "=================================")
    table.insert(lines, "")
    table.insert(lines, "No command will be executed.")
    table.insert(lines, "")
    table.insert(lines, "Install commands:")
    table.insert(lines, Packaging.setup.install_command(config))

    return table.concat(lines, "\n")
end

function Execute.confirmation(config)
    assert_valid(config)

    local split = Packaging.setup.split_packages(config)
    local total = #split.official + #split.aur

    local lines = {}

    table.insert(lines, "=================================")
    table.insert(lines, "   Grimoire V2 Installation Plan")
    table.insert(lines, "=================================")
    table.insert(lines, "")

    table.insert(lines, "Profile : " .. config.profile)
    table.insert(lines, "")

    table.insert(lines, "Packages : " .. total)
    table.insert(lines, "- Official : " .. #split.official)
    table.insert(lines, "- AUR      : " .. #split.aur)
    table.insert(lines, "")

    table.insert(lines, "Commands:")
    table.insert(lines, Packaging.setup.install_command(config))
    table.insert(lines, "")

    table.insert(lines, "No command has been executed yet.")
    table.insert(lines, "This is only a confirmation preview.")

    return table.concat(lines, "\n")
end

function Execute.export(config, filename)
    assert_valid(config)

    filename = filename or "grimoire-install-plan.sh"

    local file = io.open(filename, "w")

    if not file then
        error("Unable to create file: " .. filename)
    end

    file:write("#!/usr/bin/env bash\n\n")
    file:write("# Generated by Grimoire V2\n")
    file:write("# Profile: " .. config.profile .. "\n\n")
    file:write(Packaging.setup.install_command(config))
    file:write("\n")

    file:close()

    return filename
end

return Execute
