local Execute = {}

local Packaging = require("packaging")
local Validate = require("installer.validate")

local function assert_valid(config)
    local result = Validate.check(config)

    if result.valid then
        return true
    end

    error(
        "Invalid installation config:\n- "
            .. table.concat(result.errors, "\n- ")
    )
end

function Execute.dry_run(config)
    assert_valid(config)

    local lines = {}

    table.insert(lines, "=================================")
    table.insert(lines, "      Grimoire V2 Dry Run")
    table.insert(lines, "=================================")
    table.insert(lines, "")
    table.insert(lines, "No command will be executed.")
    table.insert(lines, "")
    table.insert(lines, "Install commands:")
    table.insert(lines, Packaging.setup.install_command(config))

    return table.concat(lines, "\n")
end

function Execute.install(config)
    assert_valid(config)

    local split = Packaging.setup.split_packages(config)
    local lines = {}

    table.insert(lines, "=================================")
    table.insert(lines, "      Grimoire V2 Install")
    table.insert(lines, "=================================")
    table.insert(lines, "")

    if #split.official > 0 then
        local command = "sudo pacman -S " .. table.concat(split.official, " ")

        table.insert(lines, "Installing official packages:")
        table.insert(lines, command)
        table.insert(lines, "")

        local result = os.execute(command)

        if result ~= true and result ~= 0 then
            error("Official package installation failed.")
        end
    else
        table.insert(lines, "No official package to install.")
        table.insert(lines, "")
    end

    if #split.aur > 0 then
        table.insert(lines, "AUR packages detected:")
        for _, package in ipairs(split.aur) do
            table.insert(lines, "- " .. package)
        end

        table.insert(lines, "")
        table.insert(lines, "AUR installation is not implemented yet.")
        table.insert(lines, "Install yay support will be handled in a later step.")
    else
        table.insert(lines, "No AUR package to install.")
    end

    return table.concat(lines, "\n")
end

function Execute.export(config, filename)
    assert_valid(config)

    filename = filename or "grimoire-install-plan.sh"

    local file = io.open(filename, "w")

    if not file then
        error("Unable to create file: " .. filename)
    end

    file:write("#!/usr/bin/env bash\n\n")
    file:write("# Generated by Grimoire V2\n")
    file:write("# Profile: " .. config.profile .. "\n\n")
    file:write(Packaging.setup.install_command(config))
    file:write("\n")

    file:close()

    return filename
end

return Execute
