package.path =
    "./?.lua;./?/init.lua;"
        .. package.path

local HyprActivationOperation = require(
    "installer.hypr_activation_operation"
)

print(
    "== HyprActivationOperation "
        .. "RC4-D10A1 Contract Test =="
)

local function shell_quote(value)
    return "'"
        .. tostring(value):gsub(
            "'",
            "'\\''"
        )
        .. "'"
end

local function command_succeeded(command)
    local ok, _, code = os.execute(command)

    return ok == true
        or ok == 0
        or code == 0
end

local function write_file(path, content)
    local file = assert(io.open(path, "wb"))
    assert(file:write(content))
    assert(file:close())
end

local temporary_directory =
    os.tmpname()

os.remove(temporary_directory)

assert(
    temporary_directory:match("^/tmp/")
)

assert(
    command_succeeded(
        "mkdir -p -- "
            .. shell_quote(
                temporary_directory
            )
    )
)

local target =
    temporary_directory
        .. "/hyprland.lua"

local loader =
    temporary_directory
        .. "/grimoire-loader.lua"

local backup =
    temporary_directory
        .. "/state/hyprland.lua.bak"

local original =
    "hl.config({ autogenerated = true })\n"

write_file(target, original)
write_file(loader, "return true\n")

local action = {
    destination = target,
    loader = loader,
    backup = backup,
    line =
        'require("grimoire-loader")',
}

local dry_run =
    HyprActivationOperation.run(
        action,
        {
            dry_run = true,
        }
    )

assert(dry_run.ok == true)
assert(dry_run.mode == "dry-run")
assert(dry_run.status == "ready")
assert(dry_run.simulated == true)
assert(dry_run.executed == false)
assert(dry_run.changed == false)
assert(type(dry_run.command) == "string")
assert(type(dry_run.compensation) == "table")

local apply_safe =
    HyprActivationOperation.run(
        action,
        {
            dry_run = false,
            apply_real = false,
        }
    )

assert(apply_safe.ok == true)
assert(apply_safe.mode == "apply-safe")
assert(apply_safe.status == "ready")
assert(apply_safe.simulated == true)
assert(apply_safe.executed == false)

local file = assert(io.open(target, "rb"))
local current = file:read("*a")
file:close()

assert(current == original)

assert(
    not command_succeeded(
        "test -e " .. shell_quote(backup)
    )
)

local missing_loader =
    HyprActivationOperation.run(
        {
            destination = target,
            loader =
                temporary_directory
                    .. "/absent.lua",
            backup = backup,
        },
        {
            dry_run = true,
        }
    )

assert(missing_loader.ok == false)

assert(
    missing_loader.status
        == "invalid-loader"
)

assert(
    command_succeeded(
        "rm -rf -- "
            .. shell_quote(
                temporary_directory
            )
    )
)

print("")
print(
    "RC4-D10A1 OK : dry-run et apply-safe "
        .. "inspectent sans modifier."
)
