package.path =
    "./?.lua;./?/init.lua;"
        .. package.path

local ActionDispatcher = require(
    "installer.action_dispatcher"
)

local ExecutionJournal = require(
    "installer.result.execution_journal"
)

print(
    "== HyprActivation RC4-D10A2 "
        .. "Dispatch Contract Test =="
)

local function shell_quote(value)
    return "'"
        .. tostring(value):gsub(
            "'",
            "'\\''"
        )
        .. "'"
end

local function command_succeeded(command)
    local ok, _, code = os.execute(command)

    return ok == true
        or ok == 0
        or code == 0
end

local function write_file(path, content)
    local file = assert(
        io.open(path, "wb")
    )

    assert(file:write(content))
    assert(file:close())
end

local temporary_directory =
    os.tmpname()

os.remove(temporary_directory)

assert(
    temporary_directory:match("^/tmp/")
)

assert(
    command_succeeded(
        "mkdir -p -- "
            .. shell_quote(
                temporary_directory
            )
    )
)

local target =
    temporary_directory
        .. "/hyprland.lua"

local loader =
    temporary_directory
        .. "/grimoire-loader.lua"

local backup =
    temporary_directory
        .. "/state/hyprland.lua.bak"

write_file(
    target,
    "hl.config({ autogenerated = true })\n"
)

write_file(loader, "return true\n")

local action = {
    type = "hypr_activation",
    manager = "deploy",
    name = "activate-hypr",
    destination = target,
    loader = loader,
    backup = backup,
    line =
        'require("grimoire-loader")',
}

local result =
    ActionDispatcher.dispatch(
        action,
        {
            dry_run = true,
        }
    )

assert(result.ok == true)
assert(result.manager == "deploy")
assert(result.actions == 1)

assert(
    type(result.details)
        == "table"
)

assert(
    type(
        result.details.hypr_activation
    ) == "table"
)

local activation =
    result.details.hypr_activation

assert(activation.ok == true)
assert(activation.mode == "dry-run")
assert(activation.status == "ready")
assert(activation.prepared == true)
assert(activation.simulated == true)
assert(activation.executed == false)
assert(type(activation.command) == "string")
assert(type(activation.compensation) == "table")

assert(
    activation.compensation.kind
        == "hypr_activation"
)

local journal =
    ExecutionJournal.create_entry(
        action,
        result,
        {
            sequence = 1,
            total = 1,
            mode = "dry-run",
        }
    )

assert(journal.type == "hypr_activation")
assert(journal.manager == "deploy")
assert(journal.name == "activate-hypr")
assert(journal.mode == "dry-run")
assert(journal.ok == true)
assert(journal.prepared == true)
assert(journal.simulated == true)
assert(journal.executed == false)
assert(type(journal.command) == "string")
assert(type(journal.compensation) == "table")

assert(
    journal.compensation.kind
        == "hypr_activation"
)

assert(
    command_succeeded(
        "rm -rf -- "
            .. shell_quote(
                temporary_directory
            )
    )
)

print("")
print(
    "RC4-D10A2 OK : ActionDispatcher "
        .. "et ExecutionJournal reconnaissent "
        .. "l’activation Hypr."
)
